---
title: My website
author: Some Person
navbar-links:
  About Me: aboutme
  Resources:
    - Kenyon Computing: https://www.kenyon.edu/academics/departments-and-majors/computing/academic-program-requirements/courses-in-computing/
  Author's home: ""
avatar: /assets/img/mango1.png
round-avatar: false
title-img: assets/img/mango1.png
social-network-links:
  github: bellablla
rss-description: isabella is taking in electronic textiles
share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false
  reddit: false
url-pretty: bellablla.github.io
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false
page-col: "#b79818"
text-col: "#bc4700"
link-col: "#d78901"
hover-col: "#d78901"
navbar-col: "#d78901"
navbar-text-col: "#bc4700"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
date_format: "%B %-d, %Y"
timezone: America/Toronto
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
kramdown:
  input: GFM
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      social-share: true
  - scope:
      path: ""
    values:
      layout: page
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
